# Site settings
title: "Herman Martinus"
email: hfbmartinus@gmail.com
description: "Code monkey, altruist, rock-climber."
baseurl: ""
url: "hermansandbox.co.za"
title_description: "Tech professional | Humanist | Rock-climber"
title_image: "https://imgur.com/naHvaoa.jpg"
google_analytics: ""
disqus_account:
github_repository: https://github.com/hermanmartinus
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: TheDrMcBadass
github_username:  HermanMartinus
instagram_username: the_sermon_of_herman
reddit_username:
linkedin_link:
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:
tumblr: "http://whypictures.com"
deviant_art: hfbmartinus
resume: "https://github.com/HermanMartinus/HermanMartinus.github.io/blob/master/resume.md#herman-martinus"

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> in Cape Town"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/hermanmartinus\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
